package app.server.httpServer.routes.logic.typeSafePersistenceHeaven.typelessHell.stupidPersistentActor.commands

import app.server.httpServer.routes.logic.typeSafePersistenceHeaven.typelessHell.state.ApplicationStateMapEntry

case class UpdateEntity_Command(updatedEntry: ApplicationStateMapEntry )
